// Generated by scripts/build-ban-card-index.js
module.exports = {
  "ancestral-recall": {
    "printId": "2398892d-28e9-4009-81ec-0d544af79d2b",
    "name": "Ancestral Recall",
    "image": "https://cards.scryfall.io/normal/front/2/3/2398892d-28e9-4009-81ec-0d544af79d2b.jpg?1783939333",
    "art": "https://cards.scryfall.io/art_crop/front/2/3/2398892d-28e9-4009-81ec-0d544af79d2b.jpg?1783939333",
    "artist": "Ryan Pancoast"
  },
  "balance": {
    "printId": "ce648aa3-098b-4af0-a433-fd290bc85904",
    "name": "Balance",
    "image": "https://cards.scryfall.io/normal/front/c/e/ce648aa3-098b-4af0-a433-fd290bc85904.jpg?1783937636",
    "art": "https://cards.scryfall.io/art_crop/front/c/e/ce648aa3-098b-4af0-a433-fd290bc85904.jpg?1783937636",
    "artist": "Kev Walker"
  },
  "black-lotus": {
    "printId": "bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd",
    "name": "Black Lotus",
    "image": "https://cards.scryfall.io/normal/front/b/d/bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd.jpg?1783939332",
    "art": "https://cards.scryfall.io/art_crop/front/b/d/bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd.jpg?1783939332",
    "artist": "Chris Rahn"
  },
  "chaos-orb": {
    "printId": "7a601041-926f-40fd-8106-39099b87806f",
    "name": "Chaos Orb",
    "image": "https://cards.scryfall.io/normal/front/7/a/7a601041-926f-40fd-8106-39099b87806f.jpg?1783948540",
    "art": "https://cards.scryfall.io/art_crop/front/7/a/7a601041-926f-40fd-8106-39099b87806f.jpg?1783948540",
    "artist": "Mark Tedin"
  },
  "channel": {
    "printId": "ce54c7c1-3401-4414-8da0-5846cb0ae1b4",
    "name": "Channel",
    "image": "https://cards.scryfall.io/normal/front/c/e/ce54c7c1-3401-4414-8da0-5846cb0ae1b4.jpg?1783935522",
    "art": "https://cards.scryfall.io/art_crop/front/c/e/ce54c7c1-3401-4414-8da0-5846cb0ae1b4.jpg?1783935522",
    "artist": "Rebecca Guay"
  },
  "dockside-extortionist": {
    "printId": "9e2e3efb-75cb-430f-b9f4-cb58f3aeb91b",
    "name": "Dockside Extortionist",
    "image": "https://cards.scryfall.io/normal/front/9/e/9e2e3efb-75cb-430f-b9f4-cb58f3aeb91b.jpg?1783921889",
    "art": "https://cards.scryfall.io/art_crop/front/9/e/9e2e3efb-75cb-430f-b9f4-cb58f3aeb91b.jpg?1783921889",
    "artist": "Lie Setiawan"
  },
  "emrakul-the-aeons-torn": {
    "printId": "249db4d4-2542-47ee-a216-e13ffbc2319c",
    "name": "Emrakul, the Aeons Torn",
    "image": "https://cards.scryfall.io/normal/front/2/4/249db4d4-2542-47ee-a216-e13ffbc2319c.jpg?1783921940",
    "art": "https://cards.scryfall.io/art_crop/front/2/4/249db4d4-2542-47ee-a216-e13ffbc2319c.jpg?1783921940",
    "artist": "Mark Tedin"
  },
  "erayo-soratami-ascendant": {
    "printId": "0b61d772-2d8b-4acf-9dd2-b2e8b03538c8",
    "name": "Erayo, Soratami Ascendant // Erayo's Essence",
    "image": "https://cards.scryfall.io/normal/front/0/b/0b61d772-2d8b-4acf-9dd2-b2e8b03538c8.jpg?1783944164",
    "art": "https://cards.scryfall.io/art_crop/front/0/b/0b61d772-2d8b-4acf-9dd2-b2e8b03538c8.jpg?1783944164",
    "artist": "Matt Cavotta"
  },
  "falling-star": {
    "printId": "f2b9983e-20d4-4d12-9e2c-ec6d9a345787",
    "name": "Falling Star",
    "image": "https://cards.scryfall.io/normal/front/f/2/f2b9983e-20d4-4d12-9e2c-ec6d9a345787.jpg?1783948056",
    "art": "https://cards.scryfall.io/art_crop/front/f/2/f2b9983e-20d4-4d12-9e2c-ec6d9a345787.jpg?1783948056",
    "artist": "Douglas Shuler"
  },
  "fastbond": {
    "printId": "daf43523-558c-4701-9fa3-5d1ceb82a006",
    "name": "Fastbond",
    "image": "https://cards.scryfall.io/normal/front/d/a/daf43523-558c-4701-9fa3-5d1ceb82a006.jpg?1783939257",
    "art": "https://cards.scryfall.io/art_crop/front/d/a/daf43523-558c-4701-9fa3-5d1ceb82a006.jpg?1783939257",
    "artist": "Nils Hamm"
  },
  "flash": {
    "printId": "d31459c2-9656-4e9a-bb72-71a910e8570b",
    "name": "Flash",
    "image": "https://cards.scryfall.io/normal/front/d/3/d31459c2-9656-4e9a-bb72-71a910e8570b.jpg?1783935178",
    "art": "https://cards.scryfall.io/art_crop/front/d/3/d31459c2-9656-4e9a-bb72-71a910e8570b.jpg?1783935178",
    "artist": "Naomi Baker"
  },
  "golos-tireless-pilgrim": {
    "printId": "1fa48620-4c3d-4f75-be1f-c12c4aa59f51",
    "name": "Golos, Tireless Pilgrim",
    "image": "https://cards.scryfall.io/normal/front/1/f/1fa48620-4c3d-4f75-be1f-c12c4aa59f51.jpg?1783932945",
    "art": "https://cards.scryfall.io/art_crop/front/1/f/1fa48620-4c3d-4f75-be1f-c12c4aa59f51.jpg?1783932945",
    "artist": "Joseph Meehan"
  },
  "griselbrand": {
    "printId": "4069e510-f3f3-4668-9f13-3546fa9bc7c3",
    "name": "Griselbrand",
    "image": "https://cards.scryfall.io/normal/front/4/0/4069e510-f3f3-4668-9f13-3546fa9bc7c3.jpg?1783908139",
    "art": "https://cards.scryfall.io/art_crop/front/4/0/4069e510-f3f3-4668-9f13-3546fa9bc7c3.jpg?1783908139",
    "artist": "Igor Kieryluk"
  },
  "hullbreacher": {
    "printId": "4df8aabc-7fcb-4b7b-980b-18f499e6c170",
    "name": "Hullbreacher",
    "image": "https://cards.scryfall.io/normal/front/4/d/4df8aabc-7fcb-4b7b-980b-18f499e6c170.jpg?1783928862",
    "art": "https://cards.scryfall.io/art_crop/front/4/d/4df8aabc-7fcb-4b7b-980b-18f499e6c170.jpg?1783928862",
    "artist": "Sidharth Chaturvedi"
  },
  "iona-shield-of-emeria": {
    "printId": "6197b59e-1652-496c-a038-e2eb88ecf017",
    "name": "Iona, Shield of Emeria",
    "image": "https://cards.scryfall.io/normal/front/6/1/6197b59e-1652-496c-a038-e2eb88ecf017.jpg?1783938426",
    "art": "https://cards.scryfall.io/art_crop/front/6/1/6197b59e-1652-496c-a038-e2eb88ecf017.jpg?1783938426",
    "artist": "Jason Chan"
  },
  "karakas": {
    "printId": "e52214e1-404a-405a-b08e-20e13c087338",
    "name": "Karakas",
    "image": "https://cards.scryfall.io/normal/front/e/5/e52214e1-404a-405a-b08e-20e13c087338.jpg?1783933757",
    "art": "https://cards.scryfall.io/art_crop/front/e/5/e52214e1-404a-405a-b08e-20e13c087338.jpg?1783933757",
    "artist": "Drew Baker"
  },
  "jeweled-lotus": {
    "printId": "d7183700-6941-4a3d-a581-4f33bea795e9",
    "name": "Jeweled Lotus",
    "image": "https://cards.scryfall.io/normal/front/d/7/d7183700-6941-4a3d-a581-4f33bea795e9.jpg?1783915595",
    "art": "https://cards.scryfall.io/art_crop/front/d/7/d7183700-6941-4a3d-a581-4f33bea795e9.jpg?1783915595",
    "artist": "Alayna Danner"
  },
  "leovold-emissary-of-trest": {
    "printId": "cedfc5b7-9242-4680-b284-debc8b5a9bc7",
    "name": "Leovold, Emissary of Trest",
    "image": "https://cards.scryfall.io/normal/front/c/e/cedfc5b7-9242-4680-b284-debc8b5a9bc7.jpg?1783933776",
    "art": "https://cards.scryfall.io/art_crop/front/c/e/cedfc5b7-9242-4680-b284-debc8b5a9bc7.jpg?1783933776",
    "artist": "Magali Villeneuve"
  },
  "library-of-alexandria": {
    "printId": "e5145f31-a4ac-44ef-8f85-e4d95f2c9ff5",
    "name": "Library of Alexandria",
    "image": "https://cards.scryfall.io/normal/front/e/5/e5145f31-a4ac-44ef-8f85-e4d95f2c9ff5.jpg?1783939222",
    "art": "https://cards.scryfall.io/art_crop/front/e/5/e5145f31-a4ac-44ef-8f85-e4d95f2c9ff5.jpg?1783939222",
    "artist": "Drew Baker"
  },
  "limited-resources": {
    "printId": "20ae3609-a3cc-486c-94f6-b8f647adfb47",
    "name": "Limited Resources",
    "image": "https://cards.scryfall.io/normal/front/2/0/20ae3609-a3cc-486c-94f6-b8f647adfb47.jpg?1783946531",
    "art": "https://cards.scryfall.io/art_crop/front/2/0/20ae3609-a3cc-486c-94f6-b8f647adfb47.jpg?1783946531",
    "artist": "Keith Parkinson"
  },
  "mana-crypt": {
    "printId": "4d960186-4559-4af0-bd22-63baa15f8939",
    "name": "Mana Crypt",
    "image": "https://cards.scryfall.io/normal/front/4/d/4d960186-4559-4af0-bd22-63baa15f8939.jpg?1783930103",
    "art": "https://cards.scryfall.io/art_crop/front/4/d/4d960186-4559-4af0-bd22-63baa15f8939.jpg?1783930103",
    "artist": "Matt Stewart"
  },
  "mox-emerald": {
    "printId": "aced2c55-7543-4076-bcdd-36c4d649b8ae",
    "name": "Mox Emerald",
    "image": "https://cards.scryfall.io/normal/front/a/c/aced2c55-7543-4076-bcdd-36c4d649b8ae.jpg?1783939332",
    "art": "https://cards.scryfall.io/art_crop/front/a/c/aced2c55-7543-4076-bcdd-36c4d649b8ae.jpg?1783939332",
    "artist": "Volkan Baǵa"
  },
  "mox-jet": {
    "printId": "5f6927e1-c580-483a-8e2a-6e2deb74800e",
    "name": "Mox Jet",
    "image": "https://cards.scryfall.io/normal/front/5/f/5f6927e1-c580-483a-8e2a-6e2deb74800e.jpg?1783939331",
    "art": "https://cards.scryfall.io/art_crop/front/5/f/5f6927e1-c580-483a-8e2a-6e2deb74800e.jpg?1783939331",
    "artist": "Volkan Baǵa"
  },
  "mox-pearl": {
    "printId": "ed0216a0-c5c9-4a99-b869-53e4d0256326",
    "name": "Mox Pearl",
    "image": "https://cards.scryfall.io/normal/front/e/d/ed0216a0-c5c9-4a99-b869-53e4d0256326.jpg?1783939331",
    "art": "https://cards.scryfall.io/art_crop/front/e/d/ed0216a0-c5c9-4a99-b869-53e4d0256326.jpg?1783939331",
    "artist": "Volkan Baǵa"
  },
  "mox-ruby": {
    "printId": "45fd6e91-df76-497f-b642-33dc3d5f6a5a",
    "name": "Mox Ruby",
    "image": "https://cards.scryfall.io/normal/front/4/5/45fd6e91-df76-497f-b642-33dc3d5f6a5a.jpg?1783939329",
    "art": "https://cards.scryfall.io/art_crop/front/4/5/45fd6e91-df76-497f-b642-33dc3d5f6a5a.jpg?1783939329",
    "artist": "Volkan Baǵa"
  },
  "mox-sapphire": {
    "printId": "ea1feac0-d3a7-45eb-9719-1cdaf51ea0b6",
    "name": "Mox Sapphire",
    "image": "https://cards.scryfall.io/normal/front/e/a/ea1feac0-d3a7-45eb-9719-1cdaf51ea0b6.jpg?1783939328",
    "art": "https://cards.scryfall.io/art_crop/front/e/a/ea1feac0-d3a7-45eb-9719-1cdaf51ea0b6.jpg?1783939328",
    "artist": "Volkan Baǵa"
  },
  "nadu-winged-wisdom": {
    "printId": "94b67489-5eb0-4406-9bf3-27e50dc632eb",
    "name": "Nadu, Winged Wisdom",
    "image": "https://cards.scryfall.io/normal/front/9/4/94b67489-5eb0-4406-9bf3-27e50dc632eb.jpg?1783911249",
    "art": "https://cards.scryfall.io/art_crop/front/9/4/94b67489-5eb0-4406-9bf3-27e50dc632eb.jpg?1783911249",
    "artist": "Daren Bader"
  },
  "paradox-engine": {
    "printId": "fd8ccd81-9e11-47fa-8e16-064c52c24506",
    "name": "Paradox Engine",
    "image": "https://cards.scryfall.io/normal/front/f/d/fd8ccd81-9e11-47fa-8e16-064c52c24506.jpg?1783936723",
    "art": "https://cards.scryfall.io/art_crop/front/f/d/fd8ccd81-9e11-47fa-8e16-064c52c24506.jpg?1783936723",
    "artist": "Christine Choi"
  },
  "primeval-titan": {
    "printId": "6d5537da-112e-4679-a113-b5d7ce32a66b",
    "name": "Primeval Titan",
    "image": "https://cards.scryfall.io/normal/front/6/d/6d5537da-112e-4679-a113-b5d7ce32a66b.jpg?1783935516",
    "art": "https://cards.scryfall.io/art_crop/front/6/d/6d5537da-112e-4679-a113-b5d7ce32a66b.jpg?1783935516",
    "artist": "Aleksi Briclot"
  },
  "prophet-of-kruphix": {
    "printId": "45de923f-fdab-460c-96f4-f62aefa9ad73",
    "name": "Prophet of Kruphix",
    "image": "https://cards.scryfall.io/normal/front/4/5/45de923f-fdab-460c-96f4-f62aefa9ad73.jpg?1783939727",
    "art": "https://cards.scryfall.io/art_crop/front/4/5/45de923f-fdab-460c-96f4-f62aefa9ad73.jpg?1783939727",
    "artist": "Winona Nelson"
  },
  "recurring-nightmare": {
    "printId": "b50e1800-a45c-43bd-8886-8a06145d9346",
    "name": "Recurring Nightmare",
    "image": "https://cards.scryfall.io/normal/front/b/5/b50e1800-a45c-43bd-8886-8a06145d9346.jpg?1783938478",
    "art": "https://cards.scryfall.io/art_crop/front/b/5/b50e1800-a45c-43bd-8886-8a06145d9346.jpg?1783938478",
    "artist": "Jeff Laubenstein"
  },
  "rofellos-llanowar-emissary": {
    "printId": "6d63a085-101c-4749-a3a4-1d335c25b10e",
    "name": "Rofellos, Llanowar Emissary",
    "image": "https://cards.scryfall.io/normal/front/6/d/6d63a085-101c-4749-a3a4-1d335c25b10e.jpg?1783939250",
    "art": "https://cards.scryfall.io/art_crop/front/6/d/6d63a085-101c-4749-a3a4-1d335c25b10e.jpg?1783939250",
    "artist": "Michael Sutfin"
  },
  "shahrazad": {
    "printId": "0014def3-4063-4929-ac51-76aef1bb2a68",
    "name": "Shahrazad",
    "image": "https://cards.scryfall.io/normal/front/0/0/0014def3-4063-4929-ac51-76aef1bb2a68.jpg?1783948393",
    "art": "https://cards.scryfall.io/art_crop/front/0/0/0014def3-4063-4929-ac51-76aef1bb2a68.jpg?1783948393",
    "artist": "Kaja Foglio"
  },
  "sundering-titan": {
    "printId": "a2ebb5d3-72b1-411d-8c90-83dac5b37898",
    "name": "Sundering Titan",
    "image": "https://cards.scryfall.io/normal/front/a/2/a2ebb5d3-72b1-411d-8c90-83dac5b37898.jpg?1783930094",
    "art": "https://cards.scryfall.io/art_crop/front/a/2/a2ebb5d3-72b1-411d-8c90-83dac5b37898.jpg?1783930094",
    "artist": "Grzegorz Rutkowski"
  },
  "sylvan-primordial": {
    "printId": "0483c869-38dc-4b0b-82f3-dd08a1ab985f",
    "name": "Sylvan Primordial",
    "image": "https://cards.scryfall.io/normal/front/0/4/0483c869-38dc-4b0b-82f3-dd08a1ab985f.jpg?1783940114",
    "art": "https://cards.scryfall.io/art_crop/front/0/4/0483c869-38dc-4b0b-82f3-dd08a1ab985f.jpg?1783940114",
    "artist": "Stephan Martiniere"
  },
  "time-vault": {
    "printId": "c367ffc1-8084-45a1-87d5-22183604d1cb",
    "name": "Time Vault",
    "image": "https://cards.scryfall.io/normal/front/c/3/c367ffc1-8084-45a1-87d5-22183604d1cb.jpg?1783939231",
    "art": "https://cards.scryfall.io/art_crop/front/c/3/c367ffc1-8084-45a1-87d5-22183604d1cb.jpg?1783939231",
    "artist": "Yeong-Hao Han"
  },
  "time-walk": {
    "printId": "70901356-3266-4bd9-aacc-f06c27271de5",
    "name": "Time Walk",
    "image": "https://cards.scryfall.io/normal/front/7/0/70901356-3266-4bd9-aacc-f06c27271de5.jpg?1783939332",
    "art": "https://cards.scryfall.io/art_crop/front/7/0/70901356-3266-4bd9-aacc-f06c27271de5.jpg?1783939332",
    "artist": "Chris Rahn"
  },
  "tinker": {
    "printId": "7da23b15-dfb8-4267-9b33-d7a4c035c434",
    "name": "Tinker",
    "image": "https://cards.scryfall.io/normal/front/7/d/7da23b15-dfb8-4267-9b33-d7a4c035c434.jpg?1783946244",
    "art": "https://cards.scryfall.io/art_crop/front/7/d/7da23b15-dfb8-4267-9b33-d7a4c035c434.jpg?1783946244",
    "artist": "Mike Raabe"
  },
  "tolarian-academy": {
    "printId": "fd99bce1-ce39-464b-8e61-2631eb3ed6f6",
    "name": "Tolarian Academy",
    "image": "https://cards.scryfall.io/normal/front/f/d/fd99bce1-ce39-464b-8e61-2631eb3ed6f6.jpg?1783939217",
    "art": "https://cards.scryfall.io/art_crop/front/f/d/fd99bce1-ce39-464b-8e61-2631eb3ed6f6.jpg?1783939217",
    "artist": "Stephen Daniele"
  },
  "trade-secrets": {
    "printId": "58dadc78-fe87-40ac-94cb-128716d89d74",
    "name": "Trade Secrets",
    "image": "https://cards.scryfall.io/normal/front/5/8/58dadc78-fe87-40ac-94cb-128716d89d74.jpg?1783941232",
    "art": "https://cards.scryfall.io/art_crop/front/5/8/58dadc78-fe87-40ac-94cb-128716d89d74.jpg?1783941232",
    "artist": "Ron Spears"
  },
  "upheaval": {
    "printId": "befe74b1-c487-42bb-a1a1-4d13f3a86ff7",
    "name": "Upheaval",
    "image": "https://cards.scryfall.io/normal/front/b/e/befe74b1-c487-42bb-a1a1-4d13f3a86ff7.jpg?1783926787",
    "art": "https://cards.scryfall.io/art_crop/front/b/e/befe74b1-c487-42bb-a1a1-4d13f3a86ff7.jpg?1783926787",
    "artist": "Kev Walker"
  },
  "yawgmoth-s-bargain": {
    "printId": "eef31b59-45bb-4208-8957-1564902c8507",
    "name": "Yawgmoth's Bargain",
    "image": "https://cards.scryfall.io/normal/front/e/e/eef31b59-45bb-4208-8957-1564902c8507.jpg?1783939281",
    "art": "https://cards.scryfall.io/art_crop/front/e/e/eef31b59-45bb-4208-8957-1564902c8507.jpg?1783939281",
    "artist": "Michael Sutfin"
  },
  "lutri-the-spellchaser": {
    "printId": "fb1189c9-7842-466e-8238-1e02677d8494",
    "name": "Lutri, the Spellchaser",
    "image": "https://cards.scryfall.io/normal/front/f/b/fb1189c9-7842-466e-8238-1e02677d8494.jpg?1783931010",
    "art": "https://cards.scryfall.io/art_crop/front/f/b/fb1189c9-7842-466e-8238-1e02677d8494.jpg?1783931010",
    "artist": "Lie Setiawan"
  }
};
