// Generated by scripts/build-hand-card-index.js
module.exports = {
  "Ad Nauseam": {
    "printId": "a9f2c53e-ff58-4aa8-89a6-4f45628cc571",
    "name": "Ad Nauseam",
    "thumb": "https://cards.scryfall.io/small/front/a/9/a9f2c53e-ff58-4aa8-89a6-4f45628cc571.jpg?1783930188",
    "image": "https://cards.scryfall.io/normal/front/a/9/a9f2c53e-ff58-4aa8-89a6-4f45628cc571.jpg?1783930188",
    "artist": "Jeremy Jarvis"
  },
  "Arid Mesa": {
    "printId": "25ac5405-df7b-4097-914a-022cb18e20d4",
    "name": "Arid Mesa",
    "thumb": "https://cards.scryfall.io/small/front/2/5/25ac5405-df7b-4097-914a-022cb18e20d4.jpg?1783926797",
    "image": "https://cards.scryfall.io/normal/front/2/5/25ac5405-df7b-4097-914a-022cb18e20d4.jpg?1783926797",
    "artist": "Raymond Swanland"
  },
  "Badlands": {
    "printId": "73403d04-fe97-4830-8b80-16dd1a1a6cc1",
    "name": "Badlands",
    "thumb": "https://cards.scryfall.io/small/front/7/3/73403d04-fe97-4830-8b80-16dd1a1a6cc1.jpg?1783939227",
    "image": "https://cards.scryfall.io/normal/front/7/3/73403d04-fe97-4830-8b80-16dd1a1a6cc1.jpg?1783939227",
    "artist": "Daarken"
  },
  "Birds of Paradise": {
    "printId": "492c2f9a-51e7-4e0f-9899-23bf43ea988b",
    "name": "Birds of Paradise",
    "thumb": "https://cards.scryfall.io/small/front/4/9/492c2f9a-51e7-4e0f-9899-23bf43ea988b.jpg?1783903230",
    "image": "https://cards.scryfall.io/normal/front/4/9/492c2f9a-51e7-4e0f-9899-23bf43ea988b.jpg?1783903230",
    "artist": "Kevin Sidharta"
  },
  "Bloodstained Mire": {
    "printId": "579743fe-f71e-4cb2-8629-d6b02ed1591d",
    "name": "Bloodstained Mire",
    "thumb": "https://cards.scryfall.io/small/front/5/7/579743fe-f71e-4cb2-8629-d6b02ed1591d.jpg?1783911241",
    "image": "https://cards.scryfall.io/normal/front/5/7/579743fe-f71e-4cb2-8629-d6b02ed1591d.jpg?1783911241",
    "artist": "Bruce Brenneise"
  },
  "Brain Freeze": {
    "printId": "3a2d7cf9-dddb-4de3-b4f2-c52e3ec8fb4b",
    "name": "Brain Freeze",
    "thumb": "https://cards.scryfall.io/small/front/3/a/3a2d7cf9-dddb-4de3-b4f2-c52e3ec8fb4b.jpg?1783939313",
    "image": "https://cards.scryfall.io/normal/front/3/a/3a2d7cf9-dddb-4de3-b4f2-c52e3ec8fb4b.jpg?1783939313",
    "artist": "Tim Hildebrandt"
  },
  "Bridgeworks Battle": {
    "printId": "ebef3db0-2b58-4581-a79c-fbca9a059e63",
    "name": "Bridgeworks Battle // Tanglespan Bridgeworks",
    "thumb": "https://cards.scryfall.io/small/front/e/b/ebef3db0-2b58-4581-a79c-fbca9a059e63.jpg?1783911228",
    "image": "https://cards.scryfall.io/normal/front/e/b/ebef3db0-2b58-4581-a79c-fbca9a059e63.jpg?1783911228",
    "artist": "Ron Spears"
  },
  "Cabal Ritual": {
    "printId": "a5d85875-22da-4054-ae42-e85b472a6d5d",
    "name": "Cabal Ritual",
    "thumb": "https://cards.scryfall.io/small/front/a/5/a5d85875-22da-4054-ae42-e85b472a6d5d.jpg?1783939296",
    "image": "https://cards.scryfall.io/normal/front/a/5/a5d85875-22da-4054-ae42-e85b472a6d5d.jpg?1783939296",
    "artist": "Greg Hildebrandt"
  },
  "Chord of Calling": {
    "printId": "b18fe7e0-8344-40cc-b242-83f01c6be7a6",
    "name": "Chord of Calling",
    "thumb": "https://cards.scryfall.io/small/front/b/1/b18fe7e0-8344-40cc-b242-83f01c6be7a6.jpg?1783913306",
    "image": "https://cards.scryfall.io/normal/front/b/1/b18fe7e0-8344-40cc-b242-83f01c6be7a6.jpg?1783913306",
    "artist": "Heather Hudson"
  },
  "Chrome Mox": {
    "printId": "f340cbf7-5bbe-45b9-a4bf-d1caa500ff93",
    "name": "Chrome Mox",
    "thumb": "https://cards.scryfall.io/small/front/f/3/f340cbf7-5bbe-45b9-a4bf-d1caa500ff93.jpg?1783930116",
    "image": "https://cards.scryfall.io/normal/front/f/3/f340cbf7-5bbe-45b9-a4bf-d1caa500ff93.jpg?1783930116",
    "artist": "Volkan Baǵa"
  },
  "City of Brass": {
    "printId": "c21565d0-fc40-4d89-9b27-87c03385e0af",
    "name": "City of Brass",
    "thumb": "https://cards.scryfall.io/small/front/c/2/c21565d0-fc40-4d89-9b27-87c03385e0af.jpg?1783904153",
    "image": "https://cards.scryfall.io/normal/front/c/2/c21565d0-fc40-4d89-9b27-87c03385e0af.jpg?1783904153",
    "artist": "Robin Olausson"
  },
  "Command Tower": {
    "printId": "0548fb60-c843-4f8f-a029-6f10efc63a41",
    "name": "Command Tower",
    "thumb": "https://cards.scryfall.io/small/front/0/5/0548fb60-c843-4f8f-a029-6f10efc63a41.jpg?1783903206",
    "image": "https://cards.scryfall.io/normal/front/0/5/0548fb60-c843-4f8f-a029-6f10efc63a41.jpg?1783903206",
    "artist": "Leon Tukker"
  },
  "Consecrated Sphinx": {
    "printId": "c9bd60fc-2777-44bc-b314-a792e8e48360",
    "name": "Consecrated Sphinx",
    "thumb": "https://cards.scryfall.io/small/front/c/9/c9bd60fc-2777-44bc-b314-a792e8e48360.jpg?1783921921",
    "image": "https://cards.scryfall.io/normal/front/c/9/c9bd60fc-2777-44bc-b314-a792e8e48360.jpg?1783921921",
    "artist": "Mark Zug"
  },
  "Copy Artifact": {
    "printId": "cd360a6c-6685-462b-8aee-b869c1e4aa89",
    "name": "Copy Artifact",
    "thumb": "https://cards.scryfall.io/small/front/c/d/cd360a6c-6685-462b-8aee-b869c1e4aa89.jpg?1783941453",
    "image": "https://cards.scryfall.io/normal/front/c/d/cd360a6c-6685-462b-8aee-b869c1e4aa89.jpg?1783941453",
    "artist": "Amy Weber"
  },
  "Dark Ritual": {
    "printId": "11e12a84-e7be-4afc-a230-c2e644743fa8",
    "name": "Dark Ritual",
    "thumb": "https://cards.scryfall.io/small/front/1/1/11e12a84-e7be-4afc-a230-c2e644743fa8.jpg?1783903013",
    "image": "https://cards.scryfall.io/normal/front/1/1/11e12a84-e7be-4afc-a230-c2e644743fa8.jpg?1783903013",
    "artist": "Nino Is"
  },
  "Deflecting Swat": {
    "printId": "b4b36435-55b3-4615-8812-af41d4fc64d9",
    "name": "Deflecting Swat",
    "thumb": "https://cards.scryfall.io/small/front/b/4/b4b36435-55b3-4615-8812-af41d4fc64d9.jpg?1783915656",
    "image": "https://cards.scryfall.io/normal/front/b/4/b4b36435-55b3-4615-8812-af41d4fc64d9.jpg?1783915656",
    "artist": "Izzy"
  },
  "Derevi, Empyrial Tactician": {
    "printId": "3a1d0dad-18a8-489e-ac11-08f64b72fda4",
    "name": "Derevi, Empyrial Tactician",
    "thumb": "https://cards.scryfall.io/small/front/3/a/3a1d0dad-18a8-489e-ac11-08f64b72fda4.jpg?1783936231",
    "image": "https://cards.scryfall.io/normal/front/3/a/3a1d0dad-18a8-489e-ac11-08f64b72fda4.jpg?1783936231",
    "artist": "Michael Komarck"
  },
  "Diabolic Intent": {
    "printId": "d72ab698-de67-4ca8-8e42-b05346bf52fa",
    "name": "Diabolic Intent",
    "thumb": "https://cards.scryfall.io/small/front/d/7/d72ab698-de67-4ca8-8e42-b05346bf52fa.jpg?1783920094",
    "image": "https://cards.scryfall.io/normal/front/d/7/d72ab698-de67-4ca8-8e42-b05346bf52fa.jpg?1783920094",
    "artist": "Dan Murayama Scott"
  },
  "Esper Sentinel": {
    "printId": "f3537373-ef54-4578-9d05-6216420ee349",
    "name": "Esper Sentinel",
    "thumb": "https://cards.scryfall.io/small/front/f/3/f3537373-ef54-4578-9d05-6216420ee349.jpg?1783926893",
    "image": "https://cards.scryfall.io/normal/front/f/3/f3537373-ef54-4578-9d05-6216420ee349.jpg?1783926893",
    "artist": "Eric Deschamps"
  },
  "Fierce Guardianship": {
    "printId": "f7f3dd95-bd14-4e0f-a388-444f9cf1b0dc",
    "name": "Fierce Guardianship",
    "thumb": "https://cards.scryfall.io/small/front/f/7/f7f3dd95-bd14-4e0f-a388-444f9cf1b0dc.jpg?1783915698",
    "image": "https://cards.scryfall.io/normal/front/f/7/f7f3dd95-bd14-4e0f-a388-444f9cf1b0dc.jpg?1783915698",
    "artist": "Randy Vargas"
  },
  "Flooded Strand": {
    "printId": "8f85e12c-196b-4459-b81f-0c9c854e9f57",
    "name": "Flooded Strand",
    "thumb": "https://cards.scryfall.io/small/front/8/f/8f85e12c-196b-4459-b81f-0c9c854e9f57.jpg?1783911240",
    "image": "https://cards.scryfall.io/normal/front/8/f/8f85e12c-196b-4459-b81f-0c9c854e9f57.jpg?1783911240",
    "artist": "Alexander Forssberg"
  },
  "Gamble": {
    "printId": "8e37fae5-ddd0-4e16-8581-71579f89d9c5",
    "name": "Gamble",
    "thumb": "https://cards.scryfall.io/small/front/8/e/8e37fae5-ddd0-4e16-8581-71579f89d9c5.jpg?1783918462",
    "image": "https://cards.scryfall.io/normal/front/8/e/8e37fae5-ddd0-4e16-8581-71579f89d9c5.jpg?1783918462",
    "artist": "Andrew Goldhawk"
  },
  "Gemstone Caverns": {
    "printId": "7f273641-c5f3-48bc-b89e-3cff52d26a0b",
    "name": "Gemstone Caverns",
    "thumb": "https://cards.scryfall.io/small/front/7/f/7f273641-c5f3-48bc-b89e-3cff52d26a0b.jpg?1783927750",
    "image": "https://cards.scryfall.io/normal/front/7/f/7f273641-c5f3-48bc-b89e-3cff52d26a0b.jpg?1783927750",
    "artist": "Martina Pilcerova"
  },
  "Gilded Drake": {
    "printId": "8de3fdae-cc2c-4a14-b15b-4fe1a983dfbf",
    "name": "Gilded Drake",
    "thumb": "https://cards.scryfall.io/small/front/8/d/8de3fdae-cc2c-4a14-b15b-4fe1a983dfbf.jpg?1783946361",
    "image": "https://cards.scryfall.io/normal/front/8/d/8de3fdae-cc2c-4a14-b15b-4fe1a983dfbf.jpg?1783946361",
    "artist": "Bob Eggleton"
  },
  "Grim Monolith": {
    "printId": "9ddc9fe1-17c8-4e1d-aeb8-c4214e881280",
    "name": "Grim Monolith",
    "thumb": "https://cards.scryfall.io/small/front/9/d/9ddc9fe1-17c8-4e1d-aeb8-c4214e881280.jpg?1783946223",
    "image": "https://cards.scryfall.io/normal/front/9/d/9ddc9fe1-17c8-4e1d-aeb8-c4214e881280.jpg?1783946223",
    "artist": "Chippy"
  },
  "Hullbreaker Horror": {
    "printId": "137acb70-a1fd-4ea9-a5d9-f4b438eb5e82",
    "name": "Hullbreaker Horror",
    "thumb": "https://cards.scryfall.io/small/front/1/3/137acb70-a1fd-4ea9-a5d9-f4b438eb5e82.jpg?1783908162",
    "image": "https://cards.scryfall.io/normal/front/1/3/137acb70-a1fd-4ea9-a5d9-f4b438eb5e82.jpg?1783908162",
    "artist": "Svetlin Velinov"
  },
  "Lotus Petal": {
    "printId": "f85ab5f9-508e-45de-8fa1-ce1f16552ffc",
    "name": "Lotus Petal",
    "thumb": "https://cards.scryfall.io/small/front/f/8/f85ab5f9-508e-45de-8fa1-ce1f16552ffc.jpg?1783938446",
    "image": "https://cards.scryfall.io/normal/front/f/8/f85ab5f9-508e-45de-8fa1-ce1f16552ffc.jpg?1783938446",
    "artist": "April Lee"
  },
  "Mana Vault": {
    "printId": "c1a31d52-a407-4ded-bfca-cc812f11afa0",
    "name": "Mana Vault",
    "thumb": "https://cards.scryfall.io/small/front/c/1/c1a31d52-a407-4ded-bfca-cc812f11afa0.jpg?1783921790",
    "image": "https://cards.scryfall.io/normal/front/c/1/c1a31d52-a407-4ded-bfca-cc812f11afa0.jpg?1783921790",
    "artist": "Christine Choi"
  },
  "Marsh Flats": {
    "printId": "9db3ba6d-eb7f-4f5b-9a3b-c6239c3baa42",
    "name": "Marsh Flats",
    "thumb": "https://cards.scryfall.io/small/front/9/d/9db3ba6d-eb7f-4f5b-9a3b-c6239c3baa42.jpg?1783926796",
    "image": "https://cards.scryfall.io/normal/front/9/d/9db3ba6d-eb7f-4f5b-9a3b-c6239c3baa42.jpg?1783926796",
    "artist": "Izzy"
  },
  "Mindbreak Trap": {
    "printId": "4f51140b-6254-431a-8810-94307bfdfbbe",
    "name": "Mindbreak Trap",
    "thumb": "https://cards.scryfall.io/small/front/4/f/4f51140b-6254-431a-8810-94307bfdfbbe.jpg?1783942162",
    "image": "https://cards.scryfall.io/normal/front/4/f/4f51140b-6254-431a-8810-94307bfdfbbe.jpg?1783942162",
    "artist": "Christopher Moeller"
  },
  "Misty Rainforest": {
    "printId": "88231c0d-0cc8-44ec-bf95-81d1710ac141",
    "name": "Misty Rainforest",
    "thumb": "https://cards.scryfall.io/small/front/8/8/88231c0d-0cc8-44ec-bf95-81d1710ac141.jpg?1783926795",
    "image": "https://cards.scryfall.io/normal/front/8/8/88231c0d-0cc8-44ec-bf95-81d1710ac141.jpg?1783926795",
    "artist": "Shelly Wan"
  },
  "Mox Amber": {
    "printId": "66024e69-ad60-4c9a-a0ca-da138d33ad80",
    "name": "Mox Amber",
    "thumb": "https://cards.scryfall.io/small/front/6/6/66024e69-ad60-4c9a-a0ca-da138d33ad80.jpg?1783934955",
    "image": "https://cards.scryfall.io/normal/front/6/6/66024e69-ad60-4c9a-a0ca-da138d33ad80.jpg?1783934955",
    "artist": "Steven Belledin"
  },
  "Mox Diamond": {
    "printId": "bf9fecfd-d122-422f-bd0a-5bf69b434dfe",
    "name": "Mox Diamond",
    "thumb": "https://cards.scryfall.io/small/front/b/f/bf9fecfd-d122-422f-bd0a-5bf69b434dfe.jpg?1783938445",
    "image": "https://cards.scryfall.io/normal/front/b/f/bf9fecfd-d122-422f-bd0a-5bf69b434dfe.jpg?1783938445",
    "artist": "Dan Frazier"
  },
  "Mystic Remora": {
    "printId": "40140991-cffa-4b52-9a25-37e9a8aa9ddd",
    "name": "Mystic Remora",
    "thumb": "https://cards.scryfall.io/small/front/4/0/40140991-cffa-4b52-9a25-37e9a8aa9ddd.jpg?1783918491",
    "image": "https://cards.scryfall.io/normal/front/4/0/40140991-cffa-4b52-9a25-37e9a8aa9ddd.jpg?1783918491",
    "artist": "Jesper Ejsing"
  },
  "Nezahal, Primal Tide": {
    "printId": "a959b40d-dd8c-49d8-8003-744d0c877b04",
    "name": "Nezahal, Primal Tide",
    "thumb": "https://cards.scryfall.io/small/front/a/9/a959b40d-dd8c-49d8-8003-744d0c877b04.jpg?1783928719",
    "image": "https://cards.scryfall.io/normal/front/a/9/a959b40d-dd8c-49d8-8003-744d0c877b04.jpg?1783928719",
    "artist": "Sam Burley"
  },
  "Otawara, Soaring City": {
    "printId": "486d7edc-d983-41f0-8b78-c99aecd72996",
    "name": "Otawara, Soaring City",
    "thumb": "https://cards.scryfall.io/small/front/4/8/486d7edc-d983-41f0-8b78-c99aecd72996.jpg?1783923816",
    "image": "https://cards.scryfall.io/normal/front/4/8/486d7edc-d983-41f0-8b78-c99aecd72996.jpg?1783923816",
    "artist": "Alayna Danner"
  },
  "Polluted Delta": {
    "printId": "6e288374-2b71-4ace-b1d2-a19fee6cb4af",
    "name": "Polluted Delta",
    "thumb": "https://cards.scryfall.io/small/front/6/e/6e288374-2b71-4ace-b1d2-a19fee6cb4af.jpg?1783911240",
    "image": "https://cards.scryfall.io/normal/front/6/e/6e288374-2b71-4ace-b1d2-a19fee6cb4af.jpg?1783911240",
    "artist": "Chris Ostrowski"
  },
  "Rhystic Study": {
    "printId": "9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b",
    "name": "Rhystic Study",
    "thumb": "https://cards.scryfall.io/small/front/9/f/9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b.jpg?1783919146",
    "image": "https://cards.scryfall.io/normal/front/9/f/9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b.jpg?1783919146",
    "artist": "Tatiana Kirgetova"
  },
  "Scalding Tarn": {
    "printId": "71e491c5-8c07-449b-b2f1-ffa052e6d311",
    "name": "Scalding Tarn",
    "thumb": "https://cards.scryfall.io/small/front/7/1/71e491c5-8c07-449b-b2f1-ffa052e6d311.jpg?1783926793",
    "image": "https://cards.scryfall.io/normal/front/7/1/71e491c5-8c07-449b-b2f1-ffa052e6d311.jpg?1783926793",
    "artist": "Philip Straub"
  },
  "Sink into Stupor": {
    "printId": "5358b87a-1a29-426d-b165-40c97da2c14d",
    "name": "Sink into Stupor // Soporific Springs",
    "thumb": "https://cards.scryfall.io/small/front/5/3/5358b87a-1a29-426d-b165-40c97da2c14d.jpg?1783911236",
    "image": "https://cards.scryfall.io/normal/front/5/3/5358b87a-1a29-426d-b165-40c97da2c14d.jpg?1783911236",
    "artist": "Peter Polach"
  },
  "Snap": {
    "printId": "f13406c6-f208-402a-94d3-a94a24f03563",
    "name": "Snap",
    "thumb": "https://cards.scryfall.io/small/front/f/1/f13406c6-f208-402a-94d3-a94a24f03563.jpg?1783918488",
    "image": "https://cards.scryfall.io/normal/front/f/1/f13406c6-f208-402a-94d3-a94a24f03563.jpg?1783918488",
    "artist": "Mike Raabe"
  },
  "Sol Ring": {
    "printId": "91fdb56b-54d5-4272-8319-505ff987fe9b",
    "name": "Sol Ring",
    "thumb": "https://cards.scryfall.io/small/front/9/1/91fdb56b-54d5-4272-8319-505ff987fe9b.jpg?1783903215",
    "image": "https://cards.scryfall.io/normal/front/9/1/91fdb56b-54d5-4272-8319-505ff987fe9b.jpg?1783903215",
    "artist": "Myles Wohl"
  },
  "Swan Song": {
    "printId": "83d0b761-d694-4232-9f40-5bd8c82a05f1",
    "name": "Swan Song",
    "thumb": "https://cards.scryfall.io/small/front/8/3/83d0b761-d694-4232-9f40-5bd8c82a05f1.jpg?1783906053",
    "image": "https://cards.scryfall.io/normal/front/8/3/83d0b761-d694-4232-9f40-5bd8c82a05f1.jpg?1783906053",
    "artist": "Lorenzo Mastroianni"
  },
  "Talisman of Curiosity": {
    "printId": "8388c4e8-bda1-47e5-8df2-ddec5babcaf9",
    "name": "Talisman of Curiosity",
    "thumb": "https://cards.scryfall.io/small/front/8/3/8388c4e8-bda1-47e5-8df2-ddec5babcaf9.jpg?1783912967",
    "image": "https://cards.scryfall.io/normal/front/8/3/8388c4e8-bda1-47e5-8df2-ddec5babcaf9.jpg?1783912967",
    "artist": "Lindsey Look"
  },
  "Talisman of Indulgence": {
    "printId": "ccacf88d-407d-465d-958a-1389b7d700e6",
    "name": "Talisman of Indulgence",
    "thumb": "https://cards.scryfall.io/small/front/c/c/ccacf88d-407d-465d-958a-1389b7d700e6.jpg?1783903211",
    "image": "https://cards.scryfall.io/normal/front/c/c/ccacf88d-407d-465d-958a-1389b7d700e6.jpg?1783903211",
    "artist": "Ioannis Fiore"
  },
  "Toxic Deluge": {
    "printId": "de5afccc-8d42-4bd6-b068-b9ea2361655e",
    "name": "Toxic Deluge",
    "thumb": "https://cards.scryfall.io/small/front/d/e/de5afccc-8d42-4bd6-b068-b9ea2361655e.jpg?1783903236",
    "image": "https://cards.scryfall.io/normal/front/d/e/de5afccc-8d42-4bd6-b068-b9ea2361655e.jpg?1783903236",
    "artist": "Anthony Devine"
  },
  "Tropical Island": {
    "printId": "47033ba4-8f26-4a6b-97bd-5b366327325e",
    "name": "Tropical Island",
    "thumb": "https://cards.scryfall.io/small/front/4/7/47033ba4-8f26-4a6b-97bd-5b366327325e.jpg?1783939216",
    "image": "https://cards.scryfall.io/normal/front/4/7/47033ba4-8f26-4a6b-97bd-5b366327325e.jpg?1783939216",
    "artist": "Franz Vohwinkel"
  },
  "Undercity Sewers": {
    "printId": "2b5801fb-2026-4f25-98bc-ebb2f99684b9",
    "name": "Undercity Sewers",
    "thumb": "https://cards.scryfall.io/small/front/2/b/2b5801fb-2026-4f25-98bc-ebb2f99684b9.jpg?1786507741",
    "image": "https://cards.scryfall.io/normal/front/2/b/2b5801fb-2026-4f25-98bc-ebb2f99684b9.jpg?1786507741",
    "artist": "Yeong-Hao Han"
  },
  "Underground Sea": {
    "printId": "26cee543-6eab-494e-a803-33a5d48d7d74",
    "name": "Underground Sea",
    "thumb": "https://cards.scryfall.io/small/front/2/6/26cee543-6eab-494e-a803-33a5d48d7d74.jpg?1783939214",
    "image": "https://cards.scryfall.io/normal/front/2/6/26cee543-6eab-494e-a803-33a5d48d7d74.jpg?1783939214",
    "artist": "Cliff Childs"
  },
  "Valley Floodcaller": {
    "printId": "90b12da0-f666-471d-95f5-15d8c9b31c92",
    "name": "Valley Floodcaller",
    "thumb": "https://cards.scryfall.io/small/front/9/0/90b12da0-f666-471d-95f5-15d8c9b31c92.jpg?1783910840",
    "image": "https://cards.scryfall.io/normal/front/9/0/90b12da0-f666-471d-95f5-15d8c9b31c92.jpg?1783910840",
    "artist": "Victor Adame Minguez"
  },
  "Void Winnower": {
    "printId": "8cbedb0a-34ca-4d42-bb43-cbea0f3c6d02",
    "name": "Void Winnower",
    "thumb": "https://cards.scryfall.io/small/front/8/c/8cbedb0a-34ca-4d42-bb43-cbea0f3c6d02.jpg?1783938221",
    "image": "https://cards.scryfall.io/normal/front/8/c/8cbedb0a-34ca-4d42-bb43-cbea0f3c6d02.jpg?1783938221",
    "artist": "Chase Stone"
  },
  "Volcanic Island": {
    "printId": "2f607e7e-30c0-45e9-8f61-bf6e9fe63f2b",
    "name": "Volcanic Island",
    "thumb": "https://cards.scryfall.io/small/front/2/f/2f607e7e-30c0-45e9-8f61-bf6e9fe63f2b.jpg?1783939216",
    "image": "https://cards.scryfall.io/normal/front/2/f/2f607e7e-30c0-45e9-8f61-bf6e9fe63f2b.jpg?1783939216",
    "artist": "Noah Bradley"
  },
  "Wheel of Fortune": {
    "printId": "2597050f-6b1b-474e-aa16-33fd154628ca",
    "name": "Wheel of Fortune",
    "thumb": "https://cards.scryfall.io/small/front/2/5/2597050f-6b1b-474e-aa16-33fd154628ca.jpg?1783939263",
    "image": "https://cards.scryfall.io/normal/front/2/5/2597050f-6b1b-474e-aa16-33fd154628ca.jpg?1783939263",
    "artist": "John Matson"
  },
  "Worldly Tutor": {
    "printId": "f39aa2e9-e294-4ce6-bf5e-e1f579101a7a",
    "name": "Worldly Tutor",
    "thumb": "https://cards.scryfall.io/small/front/f/3/f39aa2e9-e294-4ce6-bf5e-e1f579101a7a.jpg?1783918434",
    "image": "https://cards.scryfall.io/normal/front/f/3/f39aa2e9-e294-4ce6-bf5e-e1f579101a7a.jpg?1783918434",
    "artist": "Volkan Baǵa"
  }
};
