// Generated by scripts/refresh-commander-stats.js; do not edit rates by hand.
const commanderStatsManifest = {
  "source": "https://edhtop16.com/",
  "endpoint": "https://edhtop16.com/api/graphql",
  "retrievedAt": "2026-10-06T13:24:03.155Z",
  "filters": {
    "timePeriod": "SIX_MONTHS",
    "sortBy": "POPULARITY",
    "minEntries": 0,
    "minSize": 50,
    "colorId": null
  },
  "sourceRows": 652,
  "rosterRows": 100,
  "shareDenominator": 17625,
  "shareDenominatorMethod": "consistent-source-count-divided-by-metaShare",
  "conversionDefinition": "topCuts/entries",
  "winRateDefinition": "sum(wins)/sum(wins+losses+draws)",
  "winRateVerification": {
    "retrievedAt": "2026-10-06T14:13:04.653Z",
    "method": "recompute-all-roster-entry-results",
    "queryId": "f3b0fec0f117f025ead64c4eec63399f",
    "rows": 100,
    "reportSha256": "b5a7629f6e034977edea3fa9e07c259520bcdcd958e53290a8b92b0ea117e006",
    "reportFile": "edhtop16-win-rates-2026-10-06-b5a7629f6e03.json"
  }
};

const commanderStats = {
  "Kraum, Ludevic's Opus / Tymna the Weaver": {
    "entries": 1285,
    "topCuts": 307,
    "metaShare": 0.07290780141843972,
    "winRate": 0.20991686460807601
  },
  "Kinnan, Bonder Prodigy": {
    "entries": 1190,
    "topCuts": 229,
    "metaShare": 0.0675177304964539,
    "winRate": 0.2059961315280464
  },
  "Rograkh, Son of Rohgahh / Thrasios, Triton Hero": {
    "entries": 890,
    "topCuts": 185,
    "metaShare": 0.05049645390070922,
    "winRate": 0.1947130883301096
  },
  "Rograkh, Son of Rohgahh / Silas Renn, Seeker Adept": {
    "entries": 766,
    "topCuts": 123,
    "metaShare": 0.04346099290780142,
    "winRate": 0.18021472392638035
  },
  "Sisay, Weatherlight Captain": {
    "entries": 645,
    "topCuts": 158,
    "metaShare": 0.03659574468085106,
    "winRate": 0.2099125364431487
  },
  "Thrasios, Triton Hero / Tymna the Weaver": {
    "entries": 511,
    "topCuts": 112,
    "metaShare": 0.02899290780141844,
    "winRate": 0.19798657718120805
  },
  "Etali, Primal Conqueror // Etali, Primal Sickness": {
    "entries": 314,
    "topCuts": 37,
    "metaShare": 0.017815602836879434,
    "winRate": 0.14746543778801843
  },
  "Dargo, the Shipwrecker / Tymna the Weaver": {
    "entries": 369,
    "topCuts": 53,
    "metaShare": 0.020936170212765958,
    "winRate": 0.17998941238750663
  },
  "Ral, Monsoon Mage // Ral, Leyline Prodigy": {
    "entries": 370,
    "topCuts": 72,
    "metaShare": 0.02099290780141844,
    "winRate": 0.19453207150368035
  },
  "Ishai, Ojutai Dragonspeaker / Rograkh, Son of Rohgahh": {
    "entries": 389,
    "topCuts": 69,
    "metaShare": 0.022070921985815603,
    "winRate": 0.1917808219178082
  },
  "Vivi Ornitier": {
    "entries": 305,
    "topCuts": 58,
    "metaShare": 0.01730496453900709,
    "winRate": 0.18762214983713354
  },
  "Magda, Brazen Outlaw": {
    "entries": 274,
    "topCuts": 62,
    "metaShare": 0.015546099290780142,
    "winRate": 0.21314878892733563
  },
  "Thrasios, Triton Hero / Yoshimaru, Ever Faithful": {
    "entries": 255,
    "topCuts": 38,
    "metaShare": 0.01446808510638298,
    "winRate": 0.1730023273855702
  },
  "Kefka, Court Mage // Kefka, Ruler of Ruin": {
    "entries": 187,
    "topCuts": 21,
    "metaShare": 0.010609929078014184,
    "winRate": 0.1541019955654102
  },
  "Tivit, Seller of Secrets": {
    "entries": 173,
    "topCuts": 26,
    "metaShare": 0.009815602836879433,
    "winRate": 0.18602029312288612
  },
  "Lumra, Bellow of the Woods": {
    "entries": 145,
    "topCuts": 25,
    "metaShare": 0.008226950354609928,
    "winRate": 0.1945945945945946
  },
  "Tayam, Luminous Enigma": {
    "entries": 215,
    "topCuts": 41,
    "metaShare": 0.012198581560283688,
    "winRate": 0.20215633423180593
  },
  "Ob Nixilis, Captive Kingpin": {
    "entries": 204,
    "topCuts": 24,
    "metaShare": 0.011574468085106383,
    "winRate": 0.15444015444015444
  },
  "Malcolm, Keen-Eyed Navigator / Vial Smasher the Fierce": {
    "entries": 149,
    "topCuts": 32,
    "metaShare": 0.008453900709219858,
    "winRate": 0.2012987012987013
  },
  "Winota, Joiner of Forces": {
    "entries": 143,
    "topCuts": 24,
    "metaShare": 0.008113475177304964,
    "winRate": 0.17672413793103448
  },
  "Terra, Magical Adept // Esper Terra": {
    "entries": 105,
    "topCuts": 17,
    "metaShare": 0.005957446808510639,
    "winRate": 0.170018281535649
  },
  "Kenrith, the Returned King": {
    "entries": 102,
    "topCuts": 20,
    "metaShare": 0.0057872340425531915,
    "winRate": 0.16
  },
  "K'rrik, Son of Yawgmoth": {
    "entries": 128,
    "topCuts": 20,
    "metaShare": 0.007262411347517731,
    "winRate": 0.15538461538461537
  },
  "Inalla, Archmage Ritualist": {
    "entries": 119,
    "topCuts": 17,
    "metaShare": 0.00675177304964539,
    "winRate": 0.1864951768488746
  },
  "Rowan, Scion of War": {
    "entries": 118,
    "topCuts": 38,
    "metaShare": 0.006695035460992908,
    "winRate": 0.22257551669316375
  },
  "Glarb, Calamity's Augur": {
    "entries": 100,
    "topCuts": 8,
    "metaShare": 0.005673758865248227,
    "winRate": 0.12474437627811862
  },
  "Arcum Dagsson": {
    "entries": 130,
    "topCuts": 32,
    "metaShare": 0.007375886524822695,
    "winRate": 0.2398843930635838
  },
  "Zirda, the Dawnwaker": {
    "entries": 110,
    "topCuts": 30,
    "metaShare": 0.00624113475177305,
    "winRate": 0.22395833333333334
  },
  "Thrasios, Triton Hero / Vial Smasher the Fierce": {
    "entries": 96,
    "topCuts": 16,
    "metaShare": 0.005446808510638298,
    "winRate": 0.17928286852589642
  },
  "Derevi, Empyrial Tactician": {
    "entries": 77,
    "topCuts": 20,
    "metaShare": 0.004368794326241134,
    "winRate": 0.21674876847290642
  },
  "Aang, at the Crossroads // Aang, Destined Savior": {
    "entries": 89,
    "topCuts": 15,
    "metaShare": 0.005049645390070922,
    "winRate": 0.1960352422907489
  },
  "Rocco, Cabaretti Caterer": {
    "entries": 87,
    "topCuts": 20,
    "metaShare": 0.004936170212765958,
    "winRate": 0.2234513274336283
  },
  "Yuriko, the Tiger's Shadow": {
    "entries": 81,
    "topCuts": 6,
    "metaShare": 0.004595744680851064,
    "winRate": 0.125
  },
  "Brigid, Clachan's Heart // Brigid, Doun's Mind": {
    "entries": 124,
    "topCuts": 20,
    "metaShare": 0.0070354609929078014,
    "winRate": 0.19069767441860466
  },
  "Marneus Calgar": {
    "entries": 87,
    "topCuts": 14,
    "metaShare": 0.004936170212765958,
    "winRate": 0.1425287356321839
  },
  "Atraxa, Grand Unifier": {
    "entries": 70,
    "topCuts": 13,
    "metaShare": 0.003971631205673759,
    "winRate": 0.19142857142857142
  },
  "Tevesh Szat, Doom of Fools / Thrasios, Triton Hero": {
    "entries": 46,
    "topCuts": 7,
    "metaShare": 0.0026099290780141845,
    "winRate": 0.15217391304347827
  },
  "Stella Lee, Wild Card": {
    "entries": 60,
    "topCuts": 11,
    "metaShare": 0.003404255319148936,
    "winRate": 0.15517241379310345
  },
  "Urza, Lord High Artificer": {
    "entries": 61,
    "topCuts": 7,
    "metaShare": 0.0034609929078014186,
    "winRate": 0.12171052631578948
  },
  "Najeela, the Blade-Blossom": {
    "entries": 42,
    "topCuts": 7,
    "metaShare": 0.0023829787234042553,
    "winRate": 0.1813953488372093
  },
  "Norman Osborn // Green Goblin": {
    "entries": 42,
    "topCuts": 8,
    "metaShare": 0.0023829787234042553,
    "winRate": 0.15639810426540285
  },
  "Krark, the Thumbless / Sakashima of a Thousand Faces": {
    "entries": 45,
    "topCuts": 4,
    "metaShare": 0.002553191489361702,
    "winRate": 0.1504424778761062
  },
  "The Cabbage Merchant": {
    "entries": 117,
    "topCuts": 28,
    "metaShare": 0.006638297872340425,
    "winRate": 0.21724709784411278
  },
  "The Gitrog Monster": {
    "entries": 54,
    "topCuts": 9,
    "metaShare": 0.0030638297872340424,
    "winRate": 0.17518248175182483
  },
  "Scion of the Ur-Dragon": {
    "entries": 88,
    "topCuts": 23,
    "metaShare": 0.00499290780141844,
    "winRate": 0.2156448202959831
  },
  "Bjorna, Nightfall Alchemist / Wernog, Rider's Chaplain": {
    "entries": 48,
    "topCuts": 9,
    "metaShare": 0.002723404255319149,
    "winRate": 0.21929824561403508
  },
  "Malcolm, Keen-Eyed Navigator / Tymna the Weaver": {
    "entries": 40,
    "topCuts": 5,
    "metaShare": 0.0022695035460992908,
    "winRate": 0.13020833333333334
  },
  "Dihada, Binder of Wills": {
    "entries": 48,
    "topCuts": 8,
    "metaShare": 0.002723404255319149,
    "winRate": 0.1794871794871795
  },
  "Malcolm, Keen-Eyed Navigator / Tana, the Bloodsower": {
    "entries": 68,
    "topCuts": 11,
    "metaShare": 0.0038581560283687945,
    "winRate": 0.17732558139534885
  },
  "Gwenom, Remorseless": {
    "entries": 65,
    "topCuts": 13,
    "metaShare": 0.0036879432624113474,
    "winRate": 0.20987654320987653
  },
  "Kediss, Emberclaw Familiar / Malcolm, Keen-Eyed Navigator": {
    "entries": 55,
    "topCuts": 13,
    "metaShare": 0.003120567375886525,
    "winRate": 0.2348993288590604
  },
  "Maralen, Fae Ascendant": {
    "entries": 31,
    "topCuts": 5,
    "metaShare": 0.0017588652482269504,
    "winRate": 0.1032258064516129
  },
  "Korvold, Fae-Cursed King": {
    "entries": 42,
    "topCuts": 8,
    "metaShare": 0.0023829787234042553,
    "winRate": 0.17674418604651163
  },
  "Heliod, the Radiant Dawn // Heliod, the Warped Eclipse": {
    "entries": 37,
    "topCuts": 5,
    "metaShare": 0.002099290780141844,
    "winRate": 0.13978494623655913
  },
  "Akiri, Line-Slinger / Thrasios, Triton Hero": {
    "entries": 44,
    "topCuts": 9,
    "metaShare": 0.00249645390070922,
    "winRate": 0.15765765765765766
  },
  "Rakdos, the Muscle": {
    "entries": 50,
    "topCuts": 9,
    "metaShare": 0.0028368794326241137,
    "winRate": 0.18473895582329317
  },
  "Zhulodok, Void Gorger": {
    "entries": 42,
    "topCuts": 2,
    "metaShare": 0.0023829787234042553,
    "winRate": 0.15656565656565657
  },
  "Raph & Mikey, Troublemakers": {
    "entries": 80,
    "topCuts": 7,
    "metaShare": 0.0045390070921985815,
    "winRate": 0.17616580310880828
  },
  "Elsha of the Infinite": {
    "entries": 27,
    "topCuts": 4,
    "metaShare": 0.0015319148936170212,
    "winRate": 0.18518518518518517
  },
  "Leonardo, the Balance / Michelangelo, the Heart": {
    "entries": 74,
    "topCuts": 17,
    "metaShare": 0.004198581560283688,
    "winRate": 0.19437340153452684
  },
  "Shorikai, Genesis Engine": {
    "entries": 26,
    "topCuts": 4,
    "metaShare": 0.001475177304964539,
    "winRate": 0.21014492753623187
  },
  "Jhoira, Ageless Innovator": {
    "entries": 39,
    "topCuts": 11,
    "metaShare": 0.0022127659574468087,
    "winRate": 0.2634146341463415
  },
  "Y'shtola, Night's Blessed": {
    "entries": 41,
    "topCuts": 1,
    "metaShare": 0.002326241134751773,
    "winRate": 0.0979381443298969
  },
  "Talion, the Kindly Lord": {
    "entries": 23,
    "topCuts": 2,
    "metaShare": 0.0013049645390070923,
    "winRate": 0.09821428571428571
  },
  "Niv-Mizzet, Parun": {
    "entries": 17,
    "topCuts": 5,
    "metaShare": 0.0009645390070921986,
    "winRate": 0.19540229885057472
  },
  "Tasigur, the Golden Fang": {
    "entries": 22,
    "topCuts": 5,
    "metaShare": 0.00124822695035461,
    "winRate": 0.17391304347826086
  },
  "Halana, Kessig Ranger / Tymna the Weaver": {
    "entries": 29,
    "topCuts": 4,
    "metaShare": 0.0016453900709219858,
    "winRate": 0.1836734693877551
  },
  "Gyruda, Doom of Depths": {
    "entries": 30,
    "topCuts": 5,
    "metaShare": 0.001702127659574468,
    "winRate": 0.17880794701986755
  },
  "Ashling, the Limitless": {
    "entries": 26,
    "topCuts": 0,
    "metaShare": 0.001475177304964539,
    "winRate": 0.11811023622047244
  },
  "Animar, Soul of Elements": {
    "entries": 21,
    "topCuts": 4,
    "metaShare": 0.0011914893617021277,
    "winRate": 0.2018348623853211
  },
  "Celes, Rune Knight": {
    "entries": 28,
    "topCuts": 2,
    "metaShare": 0.0015886524822695035,
    "winRate": 0.13740458015267176
  },
  "Chatterfang, Squirrel General": {
    "entries": 43,
    "topCuts": 9,
    "metaShare": 0.0024397163120567374,
    "winRate": 0.17370892018779344
  },
  "The Master of Keys": {
    "entries": 19,
    "topCuts": 5,
    "metaShare": 0.001078014184397163,
    "winRate": 0.20212765957446807
  },
  "Nissa, Resurgent Animist": {
    "entries": 15,
    "topCuts": 3,
    "metaShare": 0.000851063829787234,
    "winRate": 0.136986301369863
  },
  "Narset, Enlightened Master": {
    "entries": 18,
    "topCuts": 5,
    "metaShare": 0.0010212765957446808,
    "winRate": 0.2
  },
  "Iron Man, Titan of Innovation": {
    "entries": 18,
    "topCuts": 3,
    "metaShare": 0.0010212765957446808,
    "winRate": 0.17204301075268819
  },
  "Baylen, the Haymaker": {
    "entries": 21,
    "topCuts": 7,
    "metaShare": 0.0011914893617021277,
    "winRate": 0.24770642201834864
  },
  "Avatar Aang // Aang, Master of Elements": {
    "entries": 13,
    "topCuts": 3,
    "metaShare": 0.0007375886524822695,
    "winRate": 0.2318840579710145
  },
  "Kaalia of the Vast": {
    "entries": 17,
    "topCuts": 3,
    "metaShare": 0.0009645390070921986,
    "winRate": 0.16666666666666666
  },
  "Yisan, the Wanderer Bard": {
    "entries": 27,
    "topCuts": 8,
    "metaShare": 0.0015319148936170212,
    "winRate": 0.24161073825503357
  },
  "Hashaton, Scarab's Fist": {
    "entries": 30,
    "topCuts": 6,
    "metaShare": 0.001702127659574468,
    "winRate": 0.2229299363057325
  },
  "Selvala, Explorer Returned": {
    "entries": 20,
    "topCuts": 1,
    "metaShare": 0.0011347517730496454,
    "winRate": 0.1368421052631579
  },
  "Lotho, Corrupt Shirriff": {
    "entries": 15,
    "topCuts": 2,
    "metaShare": 0.000851063829787234,
    "winRate": 0.18666666666666668
  },
  "Helga, Skittish Seer": {
    "entries": 34,
    "topCuts": 5,
    "metaShare": 0.0019290780141843972,
    "winRate": 0.18072289156626506
  },
  "Ellivere of the Wild Court": {
    "entries": 13,
    "topCuts": 1,
    "metaShare": 0.0007375886524822695,
    "winRate": 0.16129032258064516
  },
  "Kodama of the East Tree / Tymna the Weaver": {
    "entries": 19,
    "topCuts": 3,
    "metaShare": 0.001078014184397163,
    "winRate": 0.1650485436893204
  },
  "Selvala, Heart of the Wilds": {
    "entries": 13,
    "topCuts": 1,
    "metaShare": 0.0007375886524822695,
    "winRate": 0.15
  },
  "Flubs, the Fool": {
    "entries": 18,
    "topCuts": 2,
    "metaShare": 0.0010212765957446808,
    "winRate": 0.10843373493975904
  },
  "Tameshi, Reality Architect": {
    "entries": 16,
    "topCuts": 3,
    "metaShare": 0.0009078014184397163,
    "winRate": 0.14102564102564102
  },
  "Oswald Fiddlebender": {
    "entries": 24,
    "topCuts": 9,
    "metaShare": 0.0013617021276595745,
    "winRate": 0.3082706766917293
  },
  "Tatyova, Benthic Druid": {
    "entries": 4,
    "topCuts": 2,
    "metaShare": 0.00022695035460992908,
    "winRate": 0.28
  },
  "Ashling, Flame Dancer": {
    "entries": 20,
    "topCuts": 7,
    "metaShare": 0.0011347517730496454,
    "winRate": 0.20754716981132076
  },
  "Dina, Soul Steeper": {
    "entries": 6,
    "topCuts": 0,
    "metaShare": 0.00034042553191489364,
    "winRate": 0.13793103448275862
  },
  "Sami, Wildcat Captain": {
    "entries": 18,
    "topCuts": 5,
    "metaShare": 0.0010212765957446808,
    "winRate": 0.24731182795698925
  },
  "Rona, Herald of Invasion // Rona, Tolarian Obliterator": {
    "entries": 14,
    "topCuts": 3,
    "metaShare": 0.0007943262411347517,
    "winRate": 0.18571428571428572
  },
  "Captain Sisay": {
    "entries": 16,
    "topCuts": 1,
    "metaShare": 0.0009078014184397163,
    "winRate": 0.14285714285714285
  },
  "Teferi, Temporal Archmage": {
    "entries": 10,
    "topCuts": 4,
    "metaShare": 0.0005673758865248227,
    "winRate": 0.27586206896551724
  },
  "Emry, Lurker of the Loch": {
    "entries": 12,
    "topCuts": 2,
    "metaShare": 0.0006808510638297873,
    "winRate": 0.16981132075471697
  },
  "Prossh, Skyraider of Kher": {
    "entries": 3,
    "topCuts": 0,
    "metaShare": 0.00017021276595744682,
    "winRate": 0.08333333333333333
  },
  "Kykar, Wind's Fury": {
    "entries": 12,
    "topCuts": 5,
    "metaShare": 0.0006808510638297873,
    "winRate": 0.2835820895522388
  }
};

module.exports = { commanderStatsManifest, commanderStats };
