'use strict';
// Source snapshot, not a live rules feed. Updating the list creates a new voting round.
const banlist = {
  checkedAt: '2026-09-09',
  round: 'commander-2026-09-09',
  format: 'Commander',
  source: 'https://magic.wizards.com/en/banned-restricted-list',
  restrictions: [
    '所有 Conspiracy 类型牌不可使用',
    '所有涉及 ante（赌注）的牌不可使用',
    '官方列明涉及种族或文化冒犯的牌不可使用',
  ],
  cards: [
    'Ancestral Recall',
    'Balance',
    'Black Lotus',
    'Chaos Orb',
    'Channel',
    'Dockside Extortionist',
    'Emrakul, the Aeons Torn',
    'Erayo, Soratami Ascendant',
    'Falling Star',
    'Fastbond',
    'Flash',
    'Golos, Tireless Pilgrim',
    'Griselbrand',
    'Hullbreacher',
    'Iona, Shield of Emeria',
    'Karakas',
    'Jeweled Lotus',
    'Leovold, Emissary of Trest',
    'Library of Alexandria',
    'Limited Resources',
    'Mana Crypt',
    'Mox Emerald',
    'Mox Jet',
    'Mox Pearl',
    'Mox Ruby',
    'Mox Sapphire',
    'Nadu, Winged Wisdom',
    'Paradox Engine',
    'Primeval Titan',
    'Prophet of Kruphix',
    'Recurring Nightmare',
    'Rofellos, Llanowar Emissary',
    'Shahrazad',
    'Sundering Titan',
    'Sylvan Primordial',
    'Time Vault',
    'Time Walk',
    'Tinker',
    'Tolarian Academy',
    'Trade Secrets',
    'Upheaval',
    "Yawgmoth's Bargain",
  ].map((name) => ({
    id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    name,
    status: '禁用',
  })),
};
banlist.cards.push({
  id: 'lutri-the-spellchaser',
  name: 'Lutri, the Spellchaser',
  status: '仅禁作行侣',
  source:
    'https://magic.wizards.com/en/news/announcements/commander-banned-and-restricted-february-9-2026',
});

// Practice hands from public cEDH discussion. `verdict` and `reasons` restate the cited source's
// call in our own words; community votes stay separate and are never presented as the rules answer.
const handSources = {
  'play-to-win': {
    name: 'Play to Win 播客',
    title: 'TESTING cEDH OPENING HANDS TO SEE IF WE WOULD MULLIGAN',
    published: '2025-01-31',
    url: 'https://www.youtube.com/watch?v=aS1EDqC2sPg',
  },
  'topdeck-sperling': {
    name: 'Matt Sperling，TopDeck.gg',
    title: 'Can I Keep This? – How to Mulligan in cEDH',
    url: 'https://topdeck.gg/articles/can-i-keep-this-how-to-mulligan-cedh',
  },
};
const FIRST_SEVEN = '起手七张，还有免费调度';
const SECOND_SEVEN = '免费调度后的七张，再调度只剩六张';
const SEVEN = '七张起手';
const KINNAN = 'Kinnan, Bonder Prodigy';
const KINNAN_TABLE = '对手：Magda、Tymna / Thrasios、一套 Food Chain 组合技';
const ROGRAKH_SILAS = 'Rograkh, Son of Rohgahh / Silas Renn, Seeker Adept';
const ROGRAKH_TABLE = '行动顺序：Najeela、Glarb、你、Malcolm / Vial Smasher';
const TYMNA_KRAUM = "Tymna the Weaver / Kraum, Ludevic's Opus";
const TURBO_TABLE = '三位对手都是 Rograkh / Silas';
// Commanders and verdicts are interleaved so the previous answer does not give away the next one.
const hands = [
  {
    id: 'ptw-kinnan-turn-one',
    commander: KINNAN,
    short: 'Kinnan',
    seat: 3,
    stage: FIRST_SEVEN,
    table: KINNAN_TABLE,
    cards: [
      'Polluted Delta',
      'Chrome Mox',
      'Talisman of Curiosity',
      'Sink into Stupor',
      'Bridgeworks Battle',
      'Void Winnower',
      'Copy Artifact',
    ],
    verdict: 'keep',
    reasons: [
      '第 1 回合：Polluted Delta 拿地，Chrome Mox 放逐 Copy Artifact 或一张双面牌，凑出绿蓝两色施放 Kinnan',
      '第 2 回合：施放 Talisman of Curiosity；Kinnan 让 Chrome Mox 和 Talisman 各多产 1 点，付完还剩 3 点，可以留着 Sink into Stupor，或者施放 Copy Artifact',
      'Sink into Stupor 和 Bridgeworks Battle 背面都是地，缺地时可以当地打出；它们也是这套牌里少数能对付 Magda 的互动',
      '第 1 回合就有主将，第 2 回合还能留着互动，打法完整，用不着免费调度',
    ],
    source: 'play-to-win',
  },
  {
    id: 'sperling-najeela-slow',
    commander: 'Najeela, the Blade-Blossom',
    short: 'Najeela',
    seat: 3,
    stage: SECOND_SEVEN,
    table: '对手：常见的 cEDH 对局组合',
    cards: [
      'Tropical Island',
      'Deflecting Swat',
      'Rhystic Study',
      'Ad Nauseam',
      'Derevi, Empyrial Tactician',
      'City of Brass',
      'Flooded Strand',
    ],
    verdict: 'mull',
    reasons: [
      '三张地，没有任何加速：Rhystic Study、Derevi 和 Najeela 都要等到第 3 回合，Ad Nauseam 更晚',
      '单卡都很强，但展开太慢；坐在 3 号位，等这手牌准备好，别人已经在抢着赢了',
      '来源设想把 Deflecting Swat、Derevi 和 Rhystic Study 换成 Flusterstorm、Silence 和 Force of Will，结论仍是调度：互动只能帮你不输，赢不了，这手缺的是展开速度',
      '所以即使只剩六张，也要去找能更快展开的起手',
    ],
    source: 'topdeck-sperling',
  },
  {
    id: 'ptw-rograkh-silas-all-mana',
    commander: ROGRAKH_SILAS,
    short: 'Rograkh / Silas',
    seat: 3,
    stage: FIRST_SEVEN,
    table: ROGRAKH_TABLE,
    cards: [
      'Mox Amber',
      'Misty Rainforest',
      'Mox Diamond',
      'Otawara, Soaring City',
      'Volcanic Island',
      'Arid Mesa',
      'Cabal Ritual',
    ],
    verdict: 'mull',
    reasons: [
      '七张全是地和产法术力的牌，手里没有能用这些法术力去抓牌或赢的牌',
      '同样全是法术力的起手，Kinnan 可以留，因为主将自己就能把法术力变成行动；Rograkh / Silas 得靠 Ad Nauseam、Wheel of Fortune 这类牌推进，这手一张都没有',
      '还有免费调度，直接换一手',
    ],
    source: 'play-to-win',
  },
  {
    id: 'sperling-tymna-kraum-remora',
    commander: TYMNA_KRAUM,
    short: 'Tymna / Kraum',
    seat: 1,
    stage: FIRST_SEVEN,
    table: '对手：一套以生物为主、两套以咒语为主',
    cards: [
      'Mystic Remora',
      'Underground Sea',
      'Snap',
      'Badlands',
      'City of Brass',
      'Otawara, Soaring City',
      'Polluted Delta',
    ],
    verdict: 'keep',
    reasons: [
      '五张地，能施放的只有 Mystic Remora 和 Snap，看起来又慢又空',
      '但在 1 号位第 1 回合就能下 Mystic Remora：对手施放非生物咒语时不多付 4 点，你就抓一张；前几回合大家都在展开，它抓到的牌接近调度换来的牌',
      '来源特别说明：同样七张在 3、4 号位，还有免费调度时应该调度；已经是免费调度后的七张，大概还是留',
    ],
    source: 'topdeck-sperling',
  },
  {
    id: 'ptw-kinnan-no-plan',
    commander: KINNAN,
    short: 'Kinnan',
    seat: 3,
    stage: SECOND_SEVEN,
    table: KINNAN_TABLE,
    cards: [
      'Scalding Tarn',
      'Grim Monolith',
      'Gilded Drake',
      'Consecrated Sphinx',
      'Nezahal, Primal Tide',
      'Birds of Paradise',
      'Worldly Tutor',
    ],
    verdict: 'mull',
    reasons: [
      '只有一张地；第 1 回合 Birds of Paradise 不错，之后只能靠 Worldly Tutor 慢慢找牌',
      'Consecrated Sphinx 要 6 点、Nezahal 要 7 点，开局两张都是死牌',
      'Gilded Drake 能换走 Magda，或 Tymna / Thrasios 那边的 Seedborn Muse，但它要等对手先出牌，不算自己的打法；只针对一位对手，另外两位照样能赢',
      '所以即使已经用掉免费调度，也宁可调度到六张',
    ],
    source: 'play-to-win',
  },
  {
    id: 'ptw-tymna-kraum-sentinel',
    commander: TYMNA_KRAUM,
    short: 'Tymna / Kraum',
    seat: 1,
    stage: SEVEN,
    table: TURBO_TABLE,
    cards: [
      'Otawara, Soaring City',
      'Undercity Sewers',
      'Command Tower',
      'Esper Sentinel',
      'Dark Ritual',
      'Diabolic Intent',
      'Toxic Deluge',
    ],
    verdict: 'keep',
    reasons: [
      '第 1 回合用 Command Tower 施放 Esper Sentinel：对手每回合施放第一个非生物咒语时，不付 1 点你就抓一张',
      '三位对手都在拼速度，只想比别人先赢，没人会为你停下来付费；这张牌几乎每轮都能抓两三张',
      'Dark Ritual 和 Diabolic Intent 负责加速或找关键牌；缺点是没有能拦住这三套牌的互动，来源仍然选择留',
    ],
    source: 'play-to-win',
  },
  {
    id: 'ptw-rograkh-silas-wheel',
    commander: ROGRAKH_SILAS,
    short: 'Rograkh / Silas',
    seat: 3,
    stage: SEVEN,
    table: ROGRAKH_TABLE,
    cards: [
      'Lotus Petal',
      'City of Brass',
      'Bloodstained Mire',
      'Mana Vault',
      'Swan Song',
      'Valley Floodcaller',
      'Wheel of Fortune',
    ],
    verdict: 'keep',
    reasons: [
      '第 1 回合就能施放 Wheel of Fortune：City of Brass 施放 Mana Vault，用 Mana Vault 的 3 点加 Lotus Petal 付费，还剩 1 点无色',
      '有法术力，有能推进的 Wheel of Fortune，还有 Swan Song 当互动，这手可以留',
      '3 号位先 Wheel 会帮前两位补满手牌，所以看 Najeela 的开局：对手只是正常展开，就第 1 回合 Wheel 打乱他们；Najeela 已经把手牌打光，就先忍住，等第 2、3 回合法术力更多时，靠 Valley Floodcaller 让 Wheel 像有闪现一样施放，争取当回合赢',
    ],
    source: 'play-to-win',
  },
  {
    id: 'ptw-tymna-kraum-police',
    commander: TYMNA_KRAUM,
    short: 'Tymna / Kraum',
    seat: 1,
    stage: SEVEN,
    table: TURBO_TABLE,
    cards: [
      'Gemstone Caverns',
      'Marsh Flats',
      'Brain Freeze',
      'Fierce Guardianship',
      'Mindbreak Trap',
      'Gamble',
      'Deflecting Swat',
    ],
    verdict: 'mull',
    reasons: [
      '1 号位是先手牌手，Gemstone Caverns 不能在开局直接放进战场，之后当地打出也只产无色；有色法术力只能靠 Marsh Flats 找地',
      '即使之后抓到地，最早也要第 3 回合才凑出 3 点法术力施放 Tymna',
      '其余几张大多是反击和保护，只能拦别人，自己推进不了；拦下一位对手，另外两位里总有人会赢',
      '来源的原则：不留只能拦别人的起手；在 1 号位，这手牌更难成形',
    ],
    source: 'play-to-win',
  },
  {
    id: 'ptw-kinnan-mox-diamond',
    commander: KINNAN,
    short: 'Kinnan',
    seat: 3,
    stage: SEVEN,
    table: KINNAN_TABLE,
    cards: [
      'Mox Diamond',
      'Misty Rainforest',
      'Sol Ring',
      'Void Winnower',
      'Mystic Remora',
      'Hullbreaker Horror',
      'Chord of Calling',
    ],
    verdict: 'keep',
    reasons: [
      '只有一张地，Mox Diamond 进场还要弃一张地，看起来像陷阱',
      '抓到地：打出一张地，Mox Diamond 弃掉另一张，第 1 回合就能施放 Sol Ring 和 Mystic Remora；来源估计这种开局的机会接近三分之一',
      '没抓到地也照样弃掉唯一的地放 Mox Diamond：Kinnan 在场时，横置非地永久物产法术力会多产 1 点，神器法术力比地更值钱',
      'Sol Ring 和 Mystic Remora 能把大多数手牌拉到可以留；Void Winnower、Hullbreaker Horror 是后期打法，帮不了开局，要不是前几张够好，这手就该调度',
    ],
    source: 'play-to-win',
  },
  {
    id: 'ptw-rograkh-silas-no-land',
    commander: ROGRAKH_SILAS,
    short: 'Rograkh / Silas',
    seat: 3,
    stage: SECOND_SEVEN,
    table: ROGRAKH_TABLE,
    cards: [
      'Mox Amber',
      'Talisman of Indulgence',
      'Cabal Ritual',
      'Ad Nauseam',
      'Gamble',
      'Deflecting Swat',
      'Wheel of Fortune',
    ],
    verdict: 'mull',
    reasons: [
      '没有地；Rograkh 零费进场后，Mox Amber 可以产红色，只够施放 Gamble',
      'Gamble 找到牌后还要随机弃一张，找来的牌可能正好被弃；Talisman of Indulgence、Ad Nauseam、Wheel of Fortune 都得等抓到地',
      '来源说 Mana Crypt 还合法时，会用 Gamble 找它，这手就能留；Mana Crypt 已被禁，这手只要有一张地也能留，现在没有，只能调度到六张',
    ],
    source: 'play-to-win',
  },
];
function poll(id) {
  const banned = banlist.cards.find((entry) => `${banlist.round}:${entry.id}` === id);
  if (banned) return { id, choices: ['keep', 'unban', 'unknown'] };
  const hand = hands.find((entry) => `hand:${entry.id}` === id);
  return hand ? { id, choices: ['keep', 'mull', 'unknown'] } : null;
}
module.exports = { banlist, hands, handSources, poll };
